### ISSUE TITLE
vuejs webapp code is mostly empty

### ISSUE THREAD

**Issue by fbricon** [pmlopes/vertx-starter#21]
I tried to follow the steps in https://www.youtube.com/watch?v=WA9P-khaWI4 but the MainVerticle always ends up being a mostly empty main method, despite native image being unchecked. See

https://github.com/pmlopes/vertx-starter/blob/3ead19b2a21ee114a484a0b8f83a4c8c6fbc33aa/templates/verticle/src/main/java/%7BpackageDir%7D/MainVerticle.java#L29-L32

**Comment by pmlopes** [comment]
Hi @fbricon we've updated the app today, can you try to delete your local cache and try again, it looks on my side that the template is working properly again with today's update

**Comment by fbricon** [comment]
@pmlopes which local cache specifically?

**Comment by fbricon** [comment]
I still get a mostly empty MainVerticle in the downloaded project

**Comment by pmlopes** [comment]
@fbricon the issue relies on the service worker the page installs so it can be used as a desktop app even without internet connection... the problem is that this worker is caching all the page assets and the templates are still being cached preventing the download of the new ones...

Can you unregister the service worker (in your browser firefox/chrome goto [about:serviceworkers](about:serviceworkers)) and then unregister the one associated to the `vertx-starter.jetdrone.xyz` site.

After that can you reload the page, I think the new one should be fine. In the mean time I've to implement proper cache invalidation (CS hard topic :)) as there are several caches going on: browser, cloudflare and github so I believe i need to version the releases into the URLs to avoid bad states in the future...

**Comment by fbricon** [comment]
OK got it working.

Took me a while to figure out how to get the app to perform hot reloading from vscode, but I finally got it working. For those interested:
- add a main method to MainVerticle.java:
```java
  public static void main(final String[] args) {
    Launcher.executeCommand("run", MainVerticle.class.getName());//import io.vertx.core.Launcher;
  }
```
- add a launch configuration in .vscode/launch.json:
```json
{
    "configurations": [
        {
            "type": "java",
            "name": "Launch MainVerticle",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopOnEntry": false,
            "mainClass": "foo.bar.demo.MainVerticle",
            "args": "",
            "env": {
              "VERTX_HOT_RELOAD":"${workspaceFolder}/src/main/resources/webroot/dist/main.js"
            },
            "projectName": "demo"
        }
    ]
}
```
here, we simply listen to src/main/resources/webroot/dist/main.js changes, as, most likely, this file will be rebuilt by webpack on every change. Might not work 100% of the time though, but good enough for my tests.

* In a terminal, execute:

  - `./node_modules/.bin/webpack --config webpack.config.vendor.js` only once, every time node modules change
  - `./node_modules/.bin/webpack --watch` to let webpack rebuild the project assets on change

* Back to vscode, with [vscode-java-debug](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) installed, run the Debug code lens (if you want partial hot class reloading support), or just Run:
<img width="580" alt="screen shot 2018-10-09 at 4 56 50 pm" src="https://user-images.githubusercontent.com/148698/46698172-5db62400-cbe4-11e8-93f2-259fb048beca.png">

Et voila:
<img width="906" alt="screen shot 2018-10-09 at 4 58 23 pm" src="https://user-images.githubusercontent.com/148698/46698282-9655fd80-cbe4-11e8-9c3e-18d19c6ed64e.png">

**Comment by pmlopes** [comment]
I think, I'll create a `README.md` template with your comments above, that will save lots of time to other users!
