### ISSUE TITLE
Generate starter project from OpenApi 3 spec doesn't work

### ISSUE THREAD

**Issue by devrck** [pmlopes/vertx-starter#59]
I'm trying to generate a new starter project using the web interface but it gives me the error:
`Exception during code generationCannot find service name for operation getTransactionsList` I'm using the json spec from the examples.

**Comment by slinkydeveloper** [comment]
Are you trying to generate it using "OpenAPI Server with Event Bus services"? If yes, you should follow this guide: https://github.com/pmlopes/vertx-starter/blob/master/dist/webdocs/OpenAPI_Server_With_Services.md

**Comment by devrck** [comment]
Ok I will try that but then the examples repository must also be updated right?

**Comment by slinkydeveloper** [comment]
Are you talking about vertx-examples? I removed the service gen extension from it because it's related only to this project and not to vertx web api service itself.

If you want, look at this blog post: https://slinkydeveloper.com/Debts-Manager-Tutorial-Vert-x-Web-API-Contract-Service/ and at the code related: https://github.com/slinkydeveloper/debts-manager

**Comment by devrck** [comment]
Yes I was looking at https://github.com/vert-x3/vertx-examples/blob/master/web-api-service-example/src/main/resources/openapi.json as an example how to structure my OpenAPI Definition to generate a new skeleton
